--- 
qa: 
  app_revision: 2.0.0_B_24
beta: 
  app_revision: 2.0.0_RC_12
production: 
  app_revision: 1.1.0_RC_0
development: 
  app_revision: 1.1.1_D_25
testing: 
  app_revision: master
nightly: 
  app_revision: TEST_NIGHTLY_TAG
cucumber: 
  app_revision: 1.1.0_D_0
preview: 
  app_revision: 1.1.2-production
staging: 
  app_revision: 2.0.0_S_8
test: 
  app_revision: 1.1.0_D_0
